[package]
name = "icost_bill_convert"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
encoding_rs = "0.8"
encoding_rs_io = "0.1"
clap = { version = "4.5.23", features = ["derive"] }
log = "0.4"
env_logger = "0.9"
